# Generated by Django 5.0.6 on 2024-06-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_link', '0003_alter_shortlink_created_alter_shortlink_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlink',
            old_name='long_link',
            new_name='longlink',
        ),
        migrations.RenameField(
            model_name='shortlink',
            old_name='short_link',
            new_name='shortlink',
        ),
    ]
