# Generated by Django 5.0.6 on 2024-06-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_link', '0004_rename_long_link_shortlink_longlink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlink',
            old_name='longlink',
            new_name='long_link',
        ),
        migrations.RenameField(
            model_name='shortlink',
            old_name='shortlink',
            new_name='short_link',
        ),
    ]
